---
plugins:
  - jest

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
